# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabtutorial.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1178, 857)
        Dialog.setMinimumSize(QtCore.QSize(1178, 857))
        Dialog.setMaximumSize(QtCore.QSize(1178, 857))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(1142, 839))
        self.tabWidget.setMaximumSize(QtCore.QSize(1102, 16777215))
        self.tabWidget.setStyleSheet("background-color: rgb(253, 255, 242);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.foto = QtWidgets.QWidget()
        self.foto.setObjectName("foto")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.foto)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.foto)
        self.widget.setEnabled(True)
        self.widget.setMinimumSize(QtCore.QSize(1104, 823))
        self.widget.setStyleSheet("background-color: rgb(253, 255, 242);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 680, 1061, 121))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.foto_model = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.foto_model.setMinimumSize(QtCore.QSize(0, 50))
        self.foto_model.setObjectName("foto_model")
        self.horizontalLayout_2.addWidget(self.foto_model)
        self.foto_foto = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.foto_foto.setMinimumSize(QtCore.QSize(0, 50))
        self.foto_foto.setObjectName("foto_foto")
        self.horizontalLayout_2.addWidget(self.foto_foto)
        self.foto_test = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.foto_test.setMinimumSize(QtCore.QSize(0, 50))
        self.foto_test.setObjectName("foto_test")
        self.horizontalLayout_2.addWidget(self.foto_test)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(340, 0, 461, 51))
        self.label_3.setStyleSheet("font: 120 25pt \"Ubuntu Condensed\";")
        self.label_3.setLineWidth(2)
        self.label_3.setObjectName("label_3")
        self.foto_frame = QtWidgets.QLabel(self.widget)
        self.foto_frame.setGeometry(QtCore.QRect(30, 60, 1001, 581))
        self.foto_frame.setObjectName("foto_frame")
        self.verticalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.foto, "")
        self.video = QtWidgets.QWidget()
        self.video.setObjectName("video")
        self.label_2 = QtWidgets.QLabel(self.video)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 421, 51))
        self.label_2.setStyleSheet("font: 120 25pt \"Ubuntu Condensed\";")
        self.label_2.setLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.video_frame = QtWidgets.QLabel(self.video)
        self.video_frame.setGeometry(QtCore.QRect(40, 60, 1001, 581))
        self.video_frame.setObjectName("video_frame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.video)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 690, 1061, 121))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.video_model = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.video_model.setMinimumSize(QtCore.QSize(0, 50))
        self.video_model.setObjectName("video_model")
        self.horizontalLayout_3.addWidget(self.video_model)
        self.video_video = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.video_video.setMinimumSize(QtCore.QSize(0, 50))
        self.video_video.setObjectName("video_video")
        self.horizontalLayout_3.addWidget(self.video_video)
        self.video_test = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.video_test.setMinimumSize(QtCore.QSize(0, 50))
        self.video_test.setObjectName("video_test")
        self.horizontalLayout_3.addWidget(self.video_test)
        self.tabWidget.addTab(self.video, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.foto_model.setText(_translate("Dialog", "Model Yükle"))
        self.foto_foto.setText(_translate("Dialog", "Fotoğraf Yükle"))
        self.foto_test.setText(_translate("Dialog", "Test Et"))
        self.label_3.setText(_translate("Dialog", "Fotoğraf - YOLOv7  Pothole Detection "))
        self.foto_frame.setText(_translate("Dialog", "Görüntü"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.foto), _translate("Dialog", "Fotoğraf"))
        self.label_2.setText(_translate("Dialog", "Video - YOLOv7  Pothole Detection "))
        self.video_frame.setText(_translate("Dialog", "Görüntü"))
        self.video_model.setText(_translate("Dialog", "Model Yükle"))
        self.video_video.setText(_translate("Dialog", "Video Yükle"))
        self.video_test.setText(_translate("Dialog", "Test Et"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.video), _translate("Dialog", "Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
